# Generated by Django 4.2.1 on 2023-08-22 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='zone_hall',
            field=models.ForeignKey(help_text='Зона зала', on_delete=django.db.models.deletion.CASCADE, related_name='zones_hall', to='events.zonehall', verbose_name='Зона зала'),
        ),
    ]
