# Generated by Django 4.2.1 on 2023-08-22 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_ticket_zone_hall'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('guest', 'row', 'seat'), name='unique_ticket'),
        ),
    ]
