# Generated by Django 4.2.1 on 2023-08-21 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_author_alter_favorite_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='name_en',
            field=models.CharField(default=1, help_text='Город', max_length=50, unique=True, verbose_name='Город'),
            preserve_default=False,
        ),
    ]
