# Generated by Django 4.2.1 on 2023-08-22 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_city_name_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(help_text='Город', max_length=100, unique=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name_en',
            field=models.CharField(help_text='Город', max_length=50, verbose_name='Город'),
        ),
    ]
