# Generated by Django 4.2.1 on 2023-08-23 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_city_name_alter_city_name_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(help_text='Название площадки', max_length=50, verbose_name='Название площадки'),
        ),
    ]
