# Generated by Django 4.2.1 on 2023-08-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_place_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='place',
            constraint=models.UniqueConstraint(fields=('name', 'address'), name='unique_place'),
        ),
    ]
