# Generated by Django 4.2.1 on 2023-08-09 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type_event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Тип мероприятия', max_length=50, unique=True, verbose_name='Тип мероприятия')),
                ('slug', models.SlugField(help_text='Слаг типа мероприятия', unique=True, verbose_name='Слаг типа мероприятия')),
            ],
            options={
                'verbose_name': 'Тип мероприятия',
                'verbose_name_plural': 'Типы мероприятий',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название мероприятия', max_length=200, verbose_name='Название мероприятия')),
                ('discription', models.CharField(help_text='Описание мероприятия', max_length=500, verbose_name='Описание мероприятия')),
                ('date_event', models.DateField(help_text='Дата мероприятия', verbose_name='Дата мероприятия')),
                ('time_event', models.TimeField(help_text='Время мероприятия', verbose_name='Время мероприятия')),
                ('image', models.ImageField(help_text='Изображение мероприятия', upload_to='recipes/', verbose_name='Изображение мероприятия')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('type_event', models.ForeignKey(help_text='Тип мероприятия', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='event.type_event', verbose_name='Тип мероприятия')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
                'ordering': ('-pub_date',),
            },
        ),
    ]
