# Generated by Django 4.2.1 on 2023-08-10 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(help_text='Изображение мероприятия', upload_to='event/', verbose_name='Изображение мероприятия'),
        ),
    ]
