name: Django-app workflow

on:
    push:
        branches: [master, develop,dev/add-worflow-test-PEP]
    pull_request: 
        branches: [master, develop,dev/add-worflow-test-PEP]

jobs: 
    tests: 
        runs-on: ubuntu-latest

        steps: 
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v4
              with:
                python-version: '3.10' 

            - name: Install dependencies
              run: 
                python -m pip install --upgrade pip 
                pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort
                pip install -r requirements.txt
            
            - name: Test with flake8 and django tests
              run: 
                python -m flake8